import { annotateQuestion, type GlossaryAnnotation } from '../../src/lib/glossary.js';

// Presentation-only edits: keep the underlying observations and scored snapshots intact.
const wording: Record<string, string> = {
  "Approximately how many genes in the human genome code for proteins?": "How many genes in the human genome code for proteins?",
  "Approximately what share of world GDP did China account for in 2024, at market exchange rates?": "What share of world GDP did China account for in 2024, at market exchange rates?",
  "Approximately how many children per woman did the global fertility rate imply in 2023?": "What was the global fertility rate in 2023, in children per woman?",
  "In May 2022, approximately what did it cost in US dollars to sequence a human genome at NIH-funded centers?": "In May 2022, what did it cost in US dollars to sequence a human genome at NIH-funded centers?",
  "What was South Africa’s Gini coefficient in the World Bank’s 2022 estimate, on a scale from 0 to 1?": "What was South Africa’s Gini coefficient in 2022, on a scale from 0 to 1?",
  "About how many gene-editing clinical trials did CRISPR Medicine News track in February 2025?": "How many gene-editing clinical trials did CRISPR Medicine News track in February 2025?",
  "Approximately how many kilometres of high-speed railway were operating in China at the end of 2024?": "How many kilometres of high-speed railway were operating in China at the end of 2024?",
  "Approximately what percentage of Dutch land lies below sea level, according to PBL?": "What percentage of Dutch land lies below sea level?",
  "Approximately what was male life expectancy at birth in Sierra Leone in 2023?": "What was male life expectancy at birth in Sierra Leone in 2023?",
  "In Gallup’s July 2023 poll, what percentage of US adults described themselves as vegetarian?": "In July 2023, what percentage of US adults described themselves as vegetarian?",
  "How many twenty-foot equivalent units of containers did the Port of Singapore handle in 2024?": "How many twenty-foot equivalent units did the Port of Singapore handle in 2024?",
  "Approximately what share of world GDP did the United States account for in 2024, at market exchange rates?": "What share of world GDP did the United States account for in 2024, at market exchange rates?",
  "About how many nuclear warheads did the Federation of American Scientists estimate France had in July 2025?": "How many nuclear warheads was France estimated to have in July 2025?",
  "What was South Korea’s total fertility rate in the provisional figures for 2024?": "What was South Korea’s provisional total fertility rate for 2024?",
  "About how many refugees were under UNHCR’s mandate at the end of 2024?": "How many refugees were under UNHCR’s mandate at the end of 2024?",
  "What was Spain’s annual unemployment rate in 2024, according to the ILO estimate?": "What was Spain’s annual unemployment rate in 2024?",
  "Approximately what percentage of dry air is nitrogen, by volume?": "What percentage of dry air is nitrogen, by volume?",
  "In Imperva’s 2024 web-traffic analysis, what percentage of traffic came from automated bots?": "In 2024, what percentage of the web traffic measured by Imperva came from automated bots?",
  "Approximately what percentage of US electricity generation came from nuclear power in 2024?": "What percentage of US electricity generation came from nuclear power in 2024?",
  "In 2020, approximately what was the median age of the world's population?": "In 2020, what was the median age of the world's population?",
  "In the 2023 EU survey, what percentage of people aged 15 and over said they could hold a conversation in a language other than their mother tongue?": "In 2023, what percentage of people aged 15 and over in the EU said they could hold a conversation in a language other than their mother tongue?",
  "According to the UN's 2018 urbanization report, approximately what percentage of the world's population lived in urban areas in 1950?": "What percentage of the world's population lived in urban areas in 1950?",
  "According to UNCTAD's maritime trade benchmark, approximately what percentage of international trade in goods is carried by sea, by volume?": "What percentage of international trade in goods is carried by sea, by volume?",
  "In 2024, approximately what percentage of the world's electricity was generated by nuclear power?": "In 2024, what percentage of the world's electricity was generated by nuclear power?",
  "In the USGS global water inventory, what percentage of Earth's freshwater is held in ice caps, glaciers and permanent snow?": "What percentage of Earth's freshwater is held in ice caps, glaciers and permanent snow?"
};

export function questionPrompt(prompt: string): string {
  return Object.hasOwn(wording, prompt) ? wording[prompt] : prompt;
}

export function withQuestionCopy<T extends { prompt: string; glossary?: GlossaryAnnotation[] }>(question: T): T {
  const prompt = questionPrompt(question.prompt);
  if (prompt === question.prompt) return question;
  return {
    ...question,
    prompt,
    glossary: question.glossary && annotateQuestion(prompt, question.glossary.map(term => ({
      ...term, matchText: question.prompt.slice(term.start, term.end),
    }))),
  };
}
